// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqcOtLfRfDWEySvlQLnoU4sI5_-60QLwg',
    appId: '1:1074474916263:web:ebfab1d7ffff4a30abfe82',
    messagingSenderId: '1074474916263',
    projectId: 'reddit-clone-609f9',
    authDomain: 'reddit-clone-609f9.firebaseapp.com',
    storageBucket: 'reddit-clone-609f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEsy8jhWwgHsGKvlZfQ-qpMYJ3cu3FU4w',
    appId: '1:1074474916263:android:fcdb1692156f5872abfe82',
    messagingSenderId: '1074474916263',
    projectId: 'reddit-clone-609f9',
    storageBucket: 'reddit-clone-609f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyJKGqajo9uL47cEN1hC0cdIZZhoXYVg',
    appId: '1:1074474916263:ios:1dfb94481fa4ffa1abfe82',
    messagingSenderId: '1074474916263',
    projectId: 'reddit-clone-609f9',
    storageBucket: 'reddit-clone-609f9.firebasestorage.app',
    iosBundleId: 'com.example.redditDup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTyJKGqajo9uL47cEN1hC0cdIZZhoXYVg',
    appId: '1:1074474916263:ios:1dfb94481fa4ffa1abfe82',
    messagingSenderId: '1074474916263',
    projectId: 'reddit-clone-609f9',
    storageBucket: 'reddit-clone-609f9.firebasestorage.app',
    iosBundleId: 'com.example.redditDup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqcOtLfRfDWEySvlQLnoU4sI5_-60QLwg',
    appId: '1:1074474916263:web:4630d736108f376babfe82',
    messagingSenderId: '1074474916263',
    projectId: 'reddit-clone-609f9',
    authDomain: 'reddit-clone-609f9.firebaseapp.com',
    storageBucket: 'reddit-clone-609f9.firebasestorage.app',
  );
}
